version: "3.3"

services:
  redis-api:
    build: ./app
    command:
      - ./redis-api
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - GIN_MODE=release
      - REDIS_PASSWORD=avito
      - caCertFile=/tls/ca.crt
      - clientCertFile=/tls/client.crt
      - clientKeyFile=/tls/client.key
    volumes:
      - ./tests/tls:/tls
    depends_on:
      - redis

  redis:
    build: ./redis
    restart: always
    environment:
      - PASSWORD=avito
    command: "redis-server --requirepass avito --tls-port 6379 --port 0 --tls-cert-file /tls/redis.crt --tls-key-file /tls/redis.key --tls-ca-cert-file /tls/ca.crt"
    ports:
      - 6379:6379
    volumes:
      - ./tests/tls:/tls
  nginx:
    build: ./nginx
    command: "nginx"
    restart: always
    ports:
      - 8089:8089
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - redis-api