version: "3.3"

services:
  redis-api:
    build: ./app
    command:
      - ./redis-api
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - GIN_MODE=release
    depends_on:
      - redis
      - nginx
  redis:
    build: ./redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - PASSWORD=avitotech
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 8089:8089
